### ISSUE TITLE
UUID is not really an UUID

### ISSUE THREAD

**Issue by robotccm** [ccmbenchmark/ting#34]
**[Original report](https://bitbucket.org/ccmbenchmark/ting/issue/34) by Sylvain Robez-Masson (Bitbucket: [srobez-masson](https://bitbucket.org/srobez-masson), ).**

----------------------------------------

UUID named used in Ting is not really an UUID, it's an UID.
So as suggest on Slack Symfony we should do this : 

pierstoval
@syrm yes, by adding a `generateUID()` method that will do the work, and making `generateUUID()` call the `generateUID()` method. Also, make `generateUUID()` deprecated & trigger a `E_USER_DEPRECATED` error, like it's often done in many projects :slightly_smiling_face: (edited)
Like we have in Symfony, this deprecation error may say `generateUUID() method is deprecated as of version x.y and will be removed in {x+1}.0`
this way you can just rise a minor version with new method + deprecation and respect BC for all projects

**Comment by vgreb** [comment]
Closing since UUID has been removed in https://github.com/ccmbenchmark/ting/pull/90
